spring:
 batch:
  job:
   enabled: false 
 datasource:
  url: jdbc:mysql://localhost:3306/weather
  username: aashutosh
  password: Bank@123
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 properties:
  format_sql: true
logging:
  level:
    org:
      hibernate:
       SQL: DEBUG
       type:
        descriptor:
         sql:
          BasicBinder: TRACE